### ISSUE TITLE
Crash in extract-marlin-parameters.py

### ISSUE THREAD

**Issue by ggarillot** [rete/ILDCalibration#8]
Hi,

I have a crash when I try to run the first step of the calibration :

python scripts/extract-marlin-parameters.py --parameterFile steering/ild-calibration-parameters.py --steeringFile ildSteering/MarlinStdReco_ILD_l5_o2_v02_SD_PFA.xml --outputFile calibration-ild.xml
running with ElementTree on Python 2.5+
Traceback (most recent call last):
  File "scripts/extract-marlin-parameters.py", line 52, in <module>
    xmlParser = createXMLParser()
  File "/gridgroup/ilc/garillot/LCCalibration/calibration/XmlTools.py", line 34, in createXMLParser
    if etree.LXML_VERSION >= (3, 2, 1, 0):
AttributeError: 'module' object has no attribute 'LXML_VERSION' 

locate lxml
/usr/lib/python2.6/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.py
/usr/lib/python2.6/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.pyc
/usr/lib/python2.6/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.pyo
/usr/lib/python2.6/site-packages/pip/_vendor/html5lib/treewalkers/lxmletree.py
/usr/lib/python2.6/site-packages/pip/_vendor/html5lib/treewalkers/lxmletree.pyc
/usr/lib/python2.6/site-packages/pip/_vendor/html5lib/treewalkers/lxmletree.pyo

Cheers,
Guillaume

**Comment by rete** [comment]
What about : 
```shell
locate etree.so
```
?

which gives me at DESY `/usr/lib64/python2.6/site-packages/lxml/etree.so`

**Comment by ggarillot** [comment]
`locate etree.so`
gave me no results

**Comment by rete** [comment]
Print also `ls /usr/lib/python2.6/site-packages/` please.

**Comment by ggarillot** [comment]
`ls /usr/lib/python2.6/site-packages/`
`ANSI.py                           FSM.py                           mglob.pyc                   python_dateutil-1.4.1-py2.6.egg-info  site.pyc
ANSI.pyc                          FSM.pyc                          mglob.pyo                   pytz                                  site.pyo
ANSI.pyo                          FSM.pyo                          nose                        pytz-2010h-py2.6.egg-info             sos
argparse-1.2.1-py2.6.egg-info     gfal2_util                       nose-0.10.4-py2.6.egg-info  rpmUtils                              urlgrabber
argparse.py                       gfal2_util-1.0.0-py2.6.egg-info  pexpect-2.3-py2.6.egg-info  screen.py                             urlgrabber-3.9.1-py2.6.egg-info
argparse.pyc                      iniparse                         pexpect.py                  screen.pyc                            virtualenv-1.10.1-py2.6.egg-info
argparse.pyo                      iniparse-0.3.1-py2.6.egg-info    pexpect.pyc                 screen.pyo                            virtualenv.py
createrepo                        iotop                            pexpect.pyo                 setools                               virtualenv.pyc
dateutil                          iotop-0.3.2-py2.6.egg-info       pip                         setuptools                            virtualenv.pyo
distribute-0.6.10-py2.6.egg-info  IPython                          pip-7.1.0-py2.6.egg-info    setuptools-0.6c11-py2.6.egg-info      virtualenv_support
easy_install.py                   ipython-0.13.2-py2.6.egg-info    pkg_resources.py            setuptools.pth                        xcbgen
easy_install.pyc                  libproxy.py                      pkg_resources.pyc           simplegeneric-0.8-py2.6.egg-info      yum
easy_install.pyo                  libproxy.pyc                     pkg_resources.pyo           simplegeneric.py                      yumutils
fdpexpect.py                      libproxy.pyo                     pxssh.py                    simplegeneric.pyc
fdpexpect.pyc                     mglob-0.4-py2.6.egg-info         pxssh.pyc                   simplegeneric.pyo
fdpexpect.pyo                     mglob.py                         pxssh.pyo                   site.py`

**Comment by rete** [comment]
Do you have other path directories available, like `/usr/lib/python2.7` or `/usr/lib64/python2.7` ?
I suppose you are running on lyoserv ?

**Comment by ggarillot** [comment]
I am running on lyoserv yes
The only other python directory available is 
`ls /usr/lib64/python
glite_wmsui_AdWrapper.py   glite_wmsui_LbWrapper.pyc   glite_wmsui_LogWrapper.pyo  glite_wmsui_UcWrapper.py   wmsui_api.pyc     wmsui_checks.pyo    wmsui_utils.py
glite_wmsui_AdWrapper.pyc  glite_wmsui_LbWrapper.pyo   glite_wmsui_SdWrapper.py    glite_wmsui_UcWrapper.pyc  wmsui_api.pyo     wmsui_listener.py   wmsui_utils.pyc
glite_wmsui_AdWrapper.pyo  glite_wmsui_LogWrapper.py   glite_wmsui_SdWrapper.pyc   glite_wmsui_UcWrapper.pyo  wmsui_checks.py   wmsui_listener.pyc  wmsui_utils.pyo
glite_wmsui_LbWrapper.py   glite_wmsui_LogWrapper.pyc  glite_wmsui_SdWrapper.pyo   wmsui_api.py               wmsui_checks.pyc  wmsui_listener.pyo`



I just tried on my computer and the script seems to run : 

`locate etree.so
/usr/lib/python2.7/dist-packages/lxml/etree.so`

`python scripts/extract-marlin-parameters.py --parameterFile steering/ild-calibration-parameters.py --steeringFile ildSteering/MarlinStdReco_ILD_l5_o2_v02_SD_PFA.xml --outputFile calibration-ild.xml
running with lxml.etree
!!WARNING!! Processor parameter 'MyHcalBarrelDigi/calibration_mip' not found in Marlin xml file. Skipping ...
!!WARNING!! Processor parameter 'MyHcalEndcapDigi/calibration_mip' not found in Marlin xml file. Skipping ...
!!WARNING!! Processor parameter 'MyHcalRingDigi/calibration_mip' not found in Marlin xml file. Skipping ...
!!WARNING!! Processor parameter 'MyHcalBarrelReco/calibration_factorsMipGev' not found in Marlin xml file. Skipping ...
!!WARNING!! Processor parameter 'MyHcalEndcapReco/calibration_factorsMipGev' not found in Marlin xml file. Skipping ...
!!WARNING!! Processor parameter 'MyHcalRingReco/calibration_factorsMipGev' not found in Marlin xml file. Skipping ...
!!WARNING!! Processor parameter 'MySimpleMuonDigi/CalibrMUON' not found in Marlin xml file. Skipping ...`

**Comment by rete** [comment]
As usual a lot of software are missing on lyoserv. Ask to the IT group if they know where to look for.
For the warning in the running command, this is normal. Nevertheless, you will have to extract the calibration constant names and put it in the python steering file.

**Comment by rete** [comment]
You can maybe try to install lxml using pip.
Here is an article to install it without sudo rights :
http://kazhack.org/?post/2014/12/12/pip-gem-install-without-sudo

**Comment by ggarillot** [comment]
I've tried but there are still some missing packages on lyoserv ([https://stackoverflow.com/questions/5178416/pip-install-lxml-error](https://stackoverflow.com/questions/5178416/pip-install-lxml-error)) so I will ask the IT group it will be easier

**Comment by rete** [comment]
- Also if you look in this file : 
https://github.com/iLCSoft/LCCalibration/blob/master/calibration/XmlTools.py 
You will see that there are many ways to import it. I've gathered all the ways I found to do it. If lyoserv needs another way, make a pull request with a fix

**Comment by rete** [comment]
Any news on your side ?

**Comment by ggarillot** [comment]
It runs on my computer so for the moment I didn't try to fix the problem on lyoserv

**Comment by rete** [comment]
I close the issue as you were able to run it properly. If you have any trouble to run it on lyoserv because of the lxml library, please open a new issue.
Remi
